
name: CI

on: release

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run tests for Zad1
        run: python -m unittest Zad1_tests.py

      - name: Run tests for Zad2
        run: python -m unittest Zad2_tests.py
        
      - name: Run tests for Zad3
        run: python -m unittest Zad3_tests.py
        
        
        
        
