
name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
        
      - name: Run tests for Zad1
        run: python3.10 Zad1_tests.py

      - name: Run tests for Zad2
        run: python3.10 Zad2_tests.py
        
      - name: Run tests for Zad3
        run: python3.10 Zad3_tests.py
        
        
        
        
