
name: CI

on: [release, push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: path
        run: pwd
        
      - name: Run tests for Zad1
        run: python Zad1_tests.py

      - name: Run tests for Zad2
        run: python Zad2_tests.py
        
      - name: Run tests for Zad3
        run: python Zad3_tests.py
        
        
        
        
